<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>fileTypes</key>
    <array>
        <string>ds</string>
        <string>s</string>
    </array>
    <key>name</key>
    <string>DCPU16</string>
    <key>patterns</key>
    <array>
        <dict>
            <key>match</key>
            <string>;.*$</string>
            <key>name</key>
            <string>comment.line</string>
        </dict>
        <dict>
            <key>begin</key>
            <string>"</string>
            <key>beginCaptures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.string.begin.c</string>
                </dict>
            </dict>
            <key>end</key>
            <string>"</string>
            <key>endCaptures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.string.end.c</string>
                </dict>
            </dict>
            <key>name</key>
            <string>string.quoted.double.include.c</string>
        </dict>
        <dict>
            <key>match</key>
            <string>(?i)\b(set|add|sub|mul|div|mod|shl|shr|and|bor|xor|ife|ifn|ifg|ifb|jsr|dat|brk)\b</string>
            <key>name</key>
            <string>keyword.mnemonic</string>
        </dict>
        <dict>
            <key>match</key>
            <string>(?i)\b(push|pop)\b</string>
            <key>name</key>
            <string>keyword.other</string>
        </dict>
        <dict>
            <key>match</key>
            <string>^\s*\S+:</string>
            <key>name</key>
            <string>entity.name.label</string>
        </dict>
        <dict>
            <key>match</key>
            <string>^\s*:\S+\b</string>
            <key>name</key>
            <string>entity.name.label</string>
        </dict>
        <dict>
            <key>match</key>
            <string>\#define</string>
            <key>name</key>
            <string>meta.preprocessor.c</string>
        </dict>
        <dict>
            <key>match</key>
            <string>\$\S+\b</string>
            <key>name</key>
            <string>meta.preprocessor.c</string>
        </dict>
        <dict>
            <key>match</key>
            <string>\b[0-9]+\b</string>
            <key>name</key>
            <string>constant.numeric.dec</string>
        </dict>
        <dict>
            <key>match</key>
            <string>\b0x[0-9a-f]+\b</string>
            <key>name</key>
            <string>constant.numeric.hex</string>
        </dict>
        <dict>
            <key>match</key>
            <string>\b(A|B|C|X|Y|Z|I|J|SP|PC|O)+\b</string>
            <key>name</key>
            <string>storage.register</string>
        </dict>
        <dict>
            <key>match</key>
            <string>\b\S+\b</string>
            <key>name</key>
            <string>entity.name.label</string>
        </dict>
    </array>
    <key>scopeName</key>
    <string>source.asm.dcpu16</string>
    <key>uuid</key>
    <string>9C6D6AEC-813A-11E1-A4A6-00254BD734CA</string>
</dict>
</plist>